PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?term ?value
WHERE {
  ?term rdfs:label ?value .
  FILTER (REGEX(?value, "http[s]?[:]"))
  FILTER (isIRI(?term) && (REGEX(str(?term), UCASE("mp_")) || REGEX(str(?term), "http://purl.obolibrary.org/obo/MP_") || REGEX(str(?term), "http://purl.obolibrary.org/obo/mp[#]") || REGEX(str(?term), "http://purl.obolibrary.org/obo/mp-edit[#]") || REGEX(str(?term), "http://purl.obolibrary.org/obo/mp/") || REGEX(str(?term), "http://purl.obolibrary.org/obo/mp-edit/")))
}

