SELECT DISTINCT ?term
WHERE {
  { ?s1 ?p1 ?term . }
  UNION
  { ?term ?p2 ?o2 . }
  FILTER(isIRI(?term) && (regex(str(?term), UCASE("mp_")) || STRSTARTS(str(?term), "http://purl.obolibrary.org/obo/MP_") || STRSTARTS(str(?term), "http://purl.obolibrary.org/obo/mp[#]") || STRSTARTS(str(?term), "http://purl.obolibrary.org/obo/mp-edit[#]") || STRSTARTS(str(?term), "http://purl.obolibrary.org/obo/mp/") || STRSTARTS(str(?term), "http://purl.obolibrary.org/obo/mp-edit/")))
}
