SET jenkins=https://build.obolibrary.io/job/obofoundry/job/pipeline-mp/job/master/lastSuccessfulBuild/artifact/imports/
powershell -Command "Invoke-WebRequest %jenkins%chebi_import.owl -OutFile chebi_import.owl"
powershell -Command "Invoke-WebRequest %jenkins%cl_import.owl -OutFile cl_import.owl"
powershell -Command "Invoke-WebRequest %jenkins%go_import.owl -OutFile go_import.owl"
powershell -Command "Invoke-WebRequest %jenkins%mpath_import.owl -OutFile mpath_import.owl"
powershell -Command "Invoke-WebRequest %jenkins%nbo_import.owl -OutFile nbo_import.owl"
powershell -Command "Invoke-WebRequest %jenkins%pato_import.owl -OutFile pato_import.owl"
powershell -Command "Invoke-WebRequest %jenkins%pr_import.owl -OutFile pr_import.owl"
powershell -Command "Invoke-WebRequest %jenkins%ro_import.owl -OutFile ro_import.owl"
powershell -Command "Invoke-WebRequest %jenkins%uberon_import.owl -OutFile uberon_import.owl"
